### ISSUE TITLE
tf version and other package dependency

### ISSUE THREAD

**Issue by JinhuaSu** [zgzxy001/MSNET#1]
There are some environmental problems when quick starting the msnet example.

I tested tensorflow tf 2.0 and tensorflow-gpu==1.14 but failed.

**Comment by zgzxy001** [comment]
Hi, thank you for your question. The code is based on [Tensorpack](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN) and you could follow the instructions on the link to set up the environment. The gpu version that I used is 1.15.2.  We also prepared a [Demo](https://github.com/zgzxy001/MSNET/blob/master/demo.ipynb) on Google Colab, where you could run the pre-trained model on your custom images. Thanks.
