### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by so-bright** [zgzxy001/MSNET#2]
What is the environment in which the code runs

**Comment by zgzxy001** [comment]
Hi, thank you for your question. You could refer to [Issue #1](https://github.com/zgzxy001/MSNET/issues/1).

**Comment by so-bright** [comment]
thank you for your reply,
I downloaded the training model you provided and configured the environment. What command should I run in the terminal to predict.

**Comment by zgzxy001** [comment]
Hi, please refer to the [demo](https://github.com/zgzxy001/MSNET/blob/master/demo.ipynb) here.

**Comment by so-bright** [comment]
thank you
model-7400.data-00000-of-00001
model-7400.index
This is  downloaded  model file, Is this correct？
According to the demo file, i run predict.py, but have some mistake
''predict.py: error: the following arguments are required: --load''

**Comment by so-bright** [comment]
thank you
model-7400.data-00000-of-00001
model-7400.index
This is  downloaded  model file, Is this correct？
According to the demo file, i run predict.py, but have some mistake
''predict.py: error: the following arguments are required: --load''

**Comment by so-bright** [comment]
thank you
model-7400.data-00000-of-00001
model-7400.index
This is  downloaded  model file, Is this correct？
According to the demo file, i run predict.py, but have some mistake
''predict.py: error: the following arguments are required: --load''

**Comment by zgzxy001** [comment]
Yes, it is correct. Please use --load to specify the path of the model directory.

**Comment by so-bright** [comment]
how to solve this issues?

tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxBytesInUse' used by node GPUMemoryTracker/MaxBytesInUse (defined at /home/yaocheng/anaconda3/envs/yc-tensorflow/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: []
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='GPU'

         [[GPUMemoryTracker/MaxBytesInUse]]
MultiProcessMapDataZMQ successfully cleaned-up.

**Comment by zgzxy001** [comment]
Hi, I didn't meet such problems before. Feel free to check any similar issues in TensorFlow repo. Thank you.
