### ISSUE TITLE
Multi-scale Consistency Loss (MCL)

### ISSUE THREAD

**Issue by liu-vis** [zgzxy001/MSNET#3]
Dear author, thank you for the great work!
I am trying to replicate your algorithm for my research, 
but I failed to find your implementation for Multi-scale Consistency Loss (MCL).
Could you please let me know where is it? 

Thank you.

**Comment by zgzxy001** [comment]
Hi, thank you very much for your interest. The code is now available [here](https://github.com/zgzxy001/MSNET/tree/master/msnet/examples/msnet/srn). The specific implementation of MCL loss is [here](https://github.com/zgzxy001/MSNET/blob/master/msnet/examples/msnet/srn/model_utils.py#L30). Kindly note that the code is not very efficient, and I'm afraid I may not have enough time to optimize it. Sorry about that. Thank you.
